// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadTask() {
  return window['go']['main']['App']['LoadTask']();
}

export function RunGA(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunGA'](arg1, arg2, arg3);
}

export function AvailableCPUs() {
  return window['go']['main']['App']['AvailableCPUs']();
}

export function Generate(arg1) {
  return window['go']['main']['App']['Generate'](arg1);
}

export function LoadSearchResult(arg1) {
  return window['go']['main']['App']['LoadSearchResult'](arg1);
}

export function RunBCA(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunBCA'](arg1, arg2, arg3);
}

export function SaveSearchResult(arg1) {
  return window['go']['main']['App']['SaveSearchResult'](arg1);
}

export function SaveTask(arg1) {
  return window['go']['main']['App']['SaveTask'](arg1);
}

export function TSFix(arg1) {
  window['go']['main']['App']['TSFix'](arg1);
}
