// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * Generate
       * @param {models.Container} arg1 - Go Type: packing.Container
       * @returns {Promise<Array<models.Block>|Error>}  - Go Type: []packing.Block
       */
      "Generate": (arg1) => {
        return window.go.main.App.Generate(arg1);
      },
      /**
       * LoadSearchResult
       * @returns {Promise<models.SearchResult|Error>}  - Go Type: packing.SearchResult
       */
      "LoadSearchResult": () => {
        return window.go.main.App.LoadSearchResult();
      },
      /**
       * LoadTask
       * @returns {Promise<models.Task|Error>}  - Go Type: packing.Task
       */
      "LoadTask": () => {
        return window.go.main.App.LoadTask();
      },
      /**
       * RunBCA
       * @param {models.Task} arg1 - Go Type: packing.Task
       * @param {models.BCASettings} arg2 - Go Type: packing.BCASettings
       * @returns {Promise<Error>}  - Go Type: error
       */
      "RunBCA": (arg1, arg2) => {
        return window.go.main.App.RunBCA(arg1, arg2);
      },
      /**
       * RunGA
       * @param {models.Task} arg1 - Go Type: packing.Task
       * @param {models.GASettings} arg2 - Go Type: packing.GASettings
       * @returns {Promise<Error>}  - Go Type: error
       */
      "RunGA": (arg1, arg2) => {
        return window.go.main.App.RunGA(arg1, arg2);
      },
      /**
       * SaveSearchResult
       * @param {models.SearchResult} arg1 - Go Type: packing.SearchResult
       * @returns {Promise<Error>}  - Go Type: error
       */
      "SaveSearchResult": (arg1) => {
        return window.go.main.App.SaveSearchResult(arg1);
      },
      /**
       * SaveTask
       * @param {models.Task} arg1 - Go Type: packing.Task
       * @returns {Promise<Error>}  - Go Type: error
       */
      "SaveTask": (arg1) => {
        return window.go.main.App.SaveTask(arg1);
      },
    },
  },

};
export default go;
